version: "3"
services:
  flask:
    build: flask
    volumes:
      - ./src/python:/home
    command: python /home/main.py
    environment:
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "5001:5000"
  browserify:
    build: browserify
    volumes:
      - ./src/jsx:/home/src
      - ./src/python/static/js:/home/dist
    command: bash -c "cd /home && watchify -v -t [ babelify --presets [ react ] ] src/main.jsx -o dist/bundle.js"
